DROP TABLE IF EXISTS EMPLOYEE;
DROP TABLE IF EXISTS DEPARTMENT;

CREATE TABLE IF NOT EXISTS DEPARTMENT (
	DEPT_ID integer,
	NAME text,
	LOCATION text,
	PRIMARY KEY (DEPT_ID)
);

CREATE TABLE IF NOT EXISTS EMPLOYEE (
	EMP_ID integer,
	NAME text,
	SALARY number,
	DEPT_ID integer,
	PRIMARY KEY (EMP_ID),
	FOREIGN KEY (DEPT_ID) REFERENCES DEPARTMENT
);

INSERT INTO DEPARTMENT (DEPT_ID, NAME, LOCATION) VALUES (1, 'HR', 'Head-Office');
INSERT INTO DEPARTMENT (DEPT_ID, NAME, LOCATION) VALUES (2, 'Finance', 'Head-Office');
INSERT INTO DEPARTMENT (DEPT_ID, NAME, LOCATION) VALUES (3, 'Sales', 'Regional-Office');
INSERT INTO DEPARTMENT (DEPT_ID, NAME, LOCATION) VALUES (4, 'Customer Support', 'Regional-Office');
INSERT INTO DEPARTMENT (DEPT_ID, NAME, LOCATION) VALUES (5, 'Distribution', 'Regional-Office');


INSERT INTO EMPLOYEE (EMP_ID, NAME, SALARY, DEPT_ID) VALUES (1, 'Asim', 200000, 1);
INSERT INTO EMPLOYEE (EMP_ID, NAME, SALARY, DEPT_ID) VALUES (2, 'Amina', 150000, 1);
INSERT INTO EMPLOYEE (EMP_ID, NAME, SALARY, DEPT_ID) VALUES (3, 'Karim', 250000, 2);
INSERT INTO EMPLOYEE (EMP_ID, NAME, SALARY, DEPT_ID) VALUES (4, 'Salima', 180000, 2);
INSERT INTO EMPLOYEE (EMP_ID, NAME, SALARY, DEPT_ID) VALUES (5, 'Akbar', 190000, 3);
INSERT INTO EMPLOYEE (EMP_ID, NAME, SALARY, DEPT_ID) VALUES (6, 'Dilshad', 50000, 3);
INSERT INTO EMPLOYEE (EMP_ID, NAME, SALARY, DEPT_ID) VALUES (7, 'Faisal', 40000, 3);
INSERT INTO EMPLOYEE (EMP_ID, NAME, SALARY, DEPT_ID) VALUES (8, 'Farhan', 80000, 3);
INSERT INTO EMPLOYEE (EMP_ID, NAME, SALARY, DEPT_ID) VALUES (9, 'Rahim', 50000, 4);
INSERT INTO EMPLOYEE (EMP_ID, NAME, SALARY, DEPT_ID) VALUES (10, 'Asif', 50000, 4);
INSERT INTO EMPLOYEE (EMP_ID, NAME, SALARY, DEPT_ID) VALUES (11, 'Farida', 50000, 4);
INSERT INTO EMPLOYEE (EMP_ID, NAME, SALARY, DEPT_ID) VALUES (12, 'Farhana', 90000, 5);
INSERT INTO EMPLOYEE (EMP_ID, NAME, SALARY, DEPT_ID) VALUES (13, 'Asma', 50000, 5);

